# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensaje.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmensaje.proto\"\x1f\n\x07Product\x12\x14\n\x0c\x63ode_request\x18\x01 \x01(\t\"#\n\x13TransactionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x03(\t2@\n\x0eProductService\x12.\n\nAddProduct\x12\x08.Product\x1a\x14.TransactionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensaje_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=17
  _PRODUCT._serialized_end=48
  _TRANSACTIONRESPONSE._serialized_start=50
  _TRANSACTIONRESPONSE._serialized_end=85
  _PRODUCTSERVICE._serialized_start=87
  _PRODUCTSERVICE._serialized_end=151
# @@protoc_insertion_point(module_scope)
